# Generated by Django 4.0.6 on 2022-09-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshopapp', '0007_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Two wheeler with gear', 'two wheeler with gear'), ('Two wheeler without gear', 'Two wheeler without gear'), ('Four wheeler', 'Four wheeler'), ('Three Wheeler', 'Three Wheeler')], max_length=50)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_brand', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('problem_description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rep_category', models.CharField(choices=[('Repairing', 'Repairing'), ('work completed', 'Work Completed')], max_length=50)),
                ('cost', models.CharField(default=0, max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workshopapp.customer')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workshopapp.manager')),
            ],
        ),
    ]
